version: '3.8'

services:
  dashboard:
    build: .
    container_name: sentimen-dashboard
    env_file: .env
    restart: unless-stopped
    ports:
      - "8502:8501"
    volumes:
      - ./data:/app/data
      - ./tweets-data:/app/tweets-data
    networks:
      - laravel-network

networks:
  laravel-network:
    external: true
    name: bpbd_laravel-network
